IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'users')
BEGIN
    DROP TABLE users
END;

CREATE TABLE users (
    id INT NOT NULL IDENTITY,
    username VARCHAR(45) NOT NULL,
    password VARCHAR(45) NOT NULL,
    enabled INT NOT NULL
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'authorities')
BEGIN
    DROP TABLE authorities
END;

CREATE TABLE authorities (
    id INT NOT NULL IDENTITY,
    username VARCHAR(45) NOT NULL,
    authority VARCHAR(45) NOT NULL
);