IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'user')
BEGIN
    DROP TABLE [user]
END;

CREATE TABLE [user] (
    id INT NOT NULL IDENTITY,
    username VARCHAR(45) NOT NULL,
    password VARCHAR(255) NOT NULL
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'authority')
BEGIN
    DROP TABLE authority
END;

CREATE TABLE authority (
    id INT NOT NULL IDENTITY,
    name VARCHAR(45) NOT NULL,
    [user] INT NOT NULL
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'product')
BEGIN
    DROP TABLE product
END;

CREATE TABLE product (
    id INT NOT NULL IDENTITY,
    name VARCHAR(45) NOT NULL,
    price VARCHAR(45) NOT NULL,
    currency VARCHAR(45) NOT NULL
)