IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'user')
BEGIN
    DROP TABLE [user]
END;

CREATE TABLE [user] (
    id INT NOT NULL IDENTITY,
    username VARCHAR(45) NOT NULL,
    password VARCHAR(255) NOT NULL
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'authority')
BEGIN
    DROP TABLE authority
END;

CREATE TABLE authority (
    id INT NOT NULL IDENTITY,
    name VARCHAR(45) NOT NULL,
    [user] INT NOT NULL
);

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'recipe')
BEGIN
    DROP TABLE recipe
END;

CREATE TABLE recipe (
    id INT NOT NULL IDENTITY,
    title VARCHAR(45) NOT NULL,
    servings VARCHAR(45) NOT NULL,
    text VARCHAR(1000) NOT NULL
)